### PR TITLE
updates for love version 11

### PR DESCRIPTION
**Pull request by tentus**
Pretty much what the title says.

### CODE REVIEW

**Review by s-ol — APPROVED** [review]

**Comment by flamendless** [comment]
this should be merged now

**Comment by s-ol** [comment]
@flamendless I hadn't gotten to test it yet, I only approved the changes as looking right. Works flawlessly though. Thank you for the contribution @tentus!

**Comment by MikuAuahDark** [comment]
Does this handle DPI-scaling problem with canvases? because what I see is just changing the color from 0..255 to 0..1.

**Comment by s-ol** [comment]
@MikuAuahDark: I haven't tested on a high-DPI screen; if you are experiencing problems please file another issue so we can track and solve it there independently :)

**Comment by MikuAuahDark** [comment]
It's easy to test. If you have Android, chances high that the DPI scale is > 1 regardless of highdpi config flag. You can use your phone.

**Pull request merged**
